dofile(minetest.get_modpath("mysticblocks") .. "/stone.lua")

-- Initialize stone nodes

add_stone("soapstone", 128)
add_stone("rhyolite", 128)
add_stone("siltstone", 128)
add_stone("marble", 128)
add_stone("shale", 128)
add_stone("soapstone", 128)
add_stone("red_granite", 128)
add_stone("quartzite", 128)
add_stone("migmatite", 128)
add_stone("shale", 128)
add_stone("limestone", 128)
add_stone("lignite", 128)
add_stone("komatiite", 128)
add_stone("greywacke", 128)
add_stone("greenschist", 128)
add_stone("gneiss", 128)
add_stone("gabbro", 128)
add_stone("eclogite", 128)
add_stone("dolomite", 128)
add_stone("dacite", 128)
add_stone("chert", 128)
add_stone("chalk", 128)
add_stone("blueschist", 128)
add_stone("black_granite", 128)
add_stone("basalt", 128)
add_stone("andesite", 128)